/** Prepare live local editing; run after downloadCommonRepo --local. */
import fs from 'node:fs';
import path from 'node:path';
import { parseArgs } from 'node:util';
import { createOffersSync, detachJsonSource, linkFile, relativeImport, resolveJsonSource, sourceLink, writeLocalFile } from './localJson.mjs';

try {
	const { values } = parseArgs({ options: {
		'local-path': { type: 'string' },
		detach: { type: 'boolean' },
		help: { type: 'boolean', short: 'h' },
	} });
	if (values.help) {
		console.log(`Usage: pnpm linkJson [--local-path PATH] [--detach]

DOMAIN comes from the environment or .env.
ASTRO_JSON_LOCAL_PATH defaults to ../astro-json.
Links banners.json and the home page; keeps special-offers as local files.
During pnpm dev, offers are updated automatically (common → brands → site).
Use --detach to keep local copies and stop live editing (restart dev).
After changing DOMAIN, settings or source location, run local sync and linkJson again.`);
	} else if (values.detach) {
		detachJsonSource(process.cwd());
		console.log("✅ linkJson detached");
	} else {
		const root = process.cwd();
		const source = resolveJsonSource(root, values['local-path']);
		const offers = createOffersSync(root, source);
		offers.sync();
		const banners = path.join(source.siteDir, 'banners.json');
		if (fs.existsSync(banners)) linkFile(banners, path.join(root, 'src/data/site/banners.json'));
		const page = path.join(source.siteDir, 'pages/index.astro');
		if (fs.existsSync(page)) {
			const destination = path.join(root, 'src/pages/index.astro');
			writeLocalFile(destination, `---
// Generated by linkJson. Edit the source in astro-json.
import SitePage from ${JSON.stringify(relativeImport(path.dirname(destination), page))};
---
<SitePage />
`);
		}
		linkFile(source.siteDir, sourceLink(root));
		fs.rmSync(path.join(root, 'src/scss/json-source.css'), { force: true });
		console.log(`✅ linkJson: ${source.siteDir}`);
	}
} catch (error) {
	console.error(`❌ ${error.message}`);
	process.exitCode = 1;
}
