name: telegram message

# Controls when the workflow will run
on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - opened
      - synchronize
  create: {}
  delete: {}
  issues: {}
  workflow_call:
    inputs:
      additional-text:
        description: 'Additional text passed from the caller workflow'
        required: false
        type: string
    secrets:
      TELEGRAM_TO:
        description: 'Telegram ID passed from the caller workflow'
        required: true
      TELEGRAM_TOKEN:
        description: 'Telegram token passed from the caller workflow'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "build" adn "log-github-event-goodies"
  push:

    if: ${{ github.event.commits != null && inputs.additional-text == null }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Get commits
        id: get_commits
        uses: actions/checkout@v4
        with:
          # checkout full tree
          fetch-depth: 0

      - name: Prepare commit messages
        id: prepare
        run: |
          source ./.github/scripts/sh/utils.sh
          source ./.github/scripts/sh/prepare_commits.sh
          total_parts=$(prepare_commits \
            "${{ github.event.repository.name }}" \
            "${{ github.ref_name }}" \
            "${{ github.event.before }}" \
            "${{ github.sha }}" \
            "${{ github.actor }}" \
            "${{ github.repository }}")
          echo "total_parts=${total_parts}" >> $GITHUB_OUTPUT

      - name: Send messages to Telegram
        if: ${{ steps.prepare.outputs.total_parts != '0' }}
        run: |
          source ./.github/scripts/sh/utils.sh
          source ./.github/scripts/sh/send_telegram.sh
          send_telegram_messages \
            "${{ secrets.TELEGRAM_TOKEN }}" \
            "${{ secrets.TELEGRAM_TO }}" \
            "${{ steps.prepare.outputs.total_parts }}"

  create:

    if: ${{ github.event.master_branch != null && github.event.commits == null }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Send message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            *[${{ github.event.repository.name }}:${{ github.ref_name }}]* by *${{ github.actor }}*:

            added branch [${{ github.event.ref }}](https://github.com/${{ github.repository }}/tree/${{ github.event.ref }}) from [${{ github.event.master_branch }}](https://github.com/${{ github.repository }}/tree/${{ github.event.master_branch }})

  pull_request:

    if: ${{ github.event.pull_request != null }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Send message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            *[${{ github.event.repository.name }}:${{ github.ref_name }}]* by *${{ github.actor }}*:

            pull request from [${{ github.event.pull_request.head.ref }}](https://github.com/${{ github.repository }}/tree/${{ github.event.head.ref }}) to [${{ github.event.pull_request.base.ref }}](https://github.com/${{ github.repository }}/tree/${{ github.event.base.ref }}) with comment:
            ${{ github.event.pull_request.body }}

  delete:

    if: ${{ github.event.master_branch == null && github.event.commits == null && github.event.pull_request == null && inputs.additional-text == null }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Send message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            *[${{ github.event.repository.name }}:${{ github.ref_name }}]* by *${{ github.actor }}*:

            branch '`${{ github.event.ref }}`' is deleted

  get_last_commit:
    if: ${{ inputs.additional-text != null }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update repository
        run: git pull

      - name: Get last commit information
        id: get_commits
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          COMMIT_HASH=$(git rev-parse HEAD)
          echo "message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          echo "author=$COMMIT_AUTHOR" >> $GITHUB_OUTPUT
          echo "hash=$COMMIT_HASH" >> $GITHUB_OUTPUT

      - name: Set outputs
        id: set_outputs
        # The part of this solution to focus on is that we’re substituting the %, \n, and \r characters
        run: |
          additional_text=$(echo "${{ inputs.additional-text || '' }}" | base64 -d)
          if [ "$additional_text" != "" ]; then
            # Форматируем текст с переносами строк
            additional_text=$(echo -e "$additional_text")
            
            # Debug: print the formatted text
            echo "Formatted additional_text:"
            echo "$additional_text"
            
            echo "additional_text<<EOF" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "<pre>$additional_text" >> $GITHUB_OUTPUT
            echo "</pre>" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Send message to Telegram
        if: ${{ steps.get_commits.outputs.hash != '' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: html
          message: |
            <b>[${{ github.event.repository.name }}:${{ github.ref_name }}]</b> <b><a href="https://github.com/${{ github.repository }}/commit/${{ steps.get_commits.outputs.hash }}">Last commit</a></b> by <b>${{ steps.get_commits.outputs.author }}</b>
            ${{ steps.set_outputs.outputs.additional_text }}
            ${{ steps.get_commits.outputs.message }}


  # log-github-event-goodies:
  #   name: "LOG Everything on GitHub Event"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Logging
  #       run: |
  #         echo "${{ toJSON( github.event ) }}"
